name: Build Container Image
on:
  push:
    branches:
      - 'master'

jobs:
  build_image:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: docker/setup-buildx-action@v3.11.1

      - uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/yanorei32/yr32-judgesystem:latest

